/* eslint-disable */
const fs = require('fs');

module.exports = function () {
  if (!process.env.NODE_ENV) {
    process.env.NODE_ENV = 'production';
  }

  const REACT_APP = /^REACT_APP_/i;

  const clientEnv = Object.keys(process.env)
    .filter(key => REACT_APP.test(key))
    .reduce(
      (env, key) => {
        env[key] = process.env[key];
        return env;
      },
      {
        NODE_ENV: process.env.NODE_ENV,
      }
    );

  const codes = `
  // Auto-generated by build-env.js, DO NOT EDIT
  window.process = { env: ${
    JSON.stringify(clientEnv, null, 2)
  }}`.trim();

  fs.writeFileSync('./build/env.js', codes);
}
